server:
  port: 8080
spring:
  application:
    name: "Authentication"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  liquibase:
    url: jdbc:postgresql://localhost:5432/authentication
    user: admin
    password: Admin1234!
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

authentication:
  paths:
    base: "/api/v1"
    users: "/users"
    validate: "/validate"
  salary:
    min: 0
    max: 15000000

adapters:
  r2dbc:
    postgres:
      host: "localhost"
      port: 5432
      database: "authentication"
      username: "admin"
      password: "Admin1234!"
      schema: "public"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

logging:
  level:
    root: INFO
    com.onix: TRACE
