server:
  port: 8080
spring:
  application:
    name: "Authentication"
  liquibase:
    url: jdbc:postgresql://postgres:5432/authentication
    user: admin
    password: Admin1234!
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

adapters:
  r2dbc:
    postgres:
      host: "postgres"
      port: 5432
      database: "authentication"
      username: "admin"
      password: "Admin1234!"
      schema: "public"